### ISSUE TITLE
CORS Block?

### ISSUE THREAD

**Issue by rukshn** [Isuru-Nanayakkara/Vaccine-Search#1]
Interesting repo Isuru, just came to my GitHub feed.

Are you stuck with CORS policy blocking your request?

**Comment by Isuru-Nanayakkara** [comment]
Hey Rukshan! It's been a while. Hope you're doing good.

Haven't done any web dev stuff in years. Came across this [site](https://vaccine.covid19.gov.lk/sign-in) and I just wanted to tinker with web stuff and add a few extra functionalities like a search and easy sharing etc. Nothing too crazy.

You're right. I was stuck on the CORS issue for a couple of days. I tried routing the request through a proxy and even that didn't work. Turns out the server seems to be blocking access to the API based on the IP addresses. It only works within Sri Lanka. I tried viewing the site through a VPN and even that doesn't load.

I kind of abandoned the project yesterday because I'm kind of out of ideas on how to proceed 😅

Know any tricks on how to bypass a IP address validation?

**Comment by rukshn** [comment]
The only option I can think of is run a local curl request, and post the output to your own server and allow the front-end to use that data.

You can set up a cron job to automate this maybe once an hour, I don't see any other way that you can do it.

Running a fetch request from the front-end will not do, due to the CORS block. Only way is to curl it or curl it via PHP.

**Comment by Isuru-Nanayakkara** [comment]
Gotcha. Thanks!

I did think out loud about routing the API through a PHP script hosted on a [local server](https://www.akaza.lk) but then again, since this is a silly pet-project, I don't wanna go that far.

I don't own any server space local or otherwise at the moment so having an intermediate database is not feasible either. But let's see.

Thanks for the input, Rukshan. Appreciate it! 🙂

**Comment by rukshn** [comment]
Yeah I know not worth the time and effort
